export interface PublicDocumentLink {
  label: string;
  href: string;
}

export interface PublicDocumentSection {
  title: string;
  content: string[];
  list?: boolean;
  links?: PublicDocumentLink[];
}

export interface PublicDocument {
  eyebrow: string;
  title: string;
  lastUpdated?: string;
  introduction?: string;
  sections: PublicDocumentSection[];
  closing?: string;
}

export const publicDocuments: Record<"terms" | "legal" | "contact" | "socials", PublicDocument> = {
  terms: {
    eyebrow: "Legal",
    title: "Terms of Service",
    lastUpdated: "13.07.2026",
    introduction:
      'These Terms of Service ("Terms") govern your use of Converza (the "Service"). By creating an account or using the Service, you agree to these Terms.',
    sections: [
      {
        title: "The Service",
        content: [
          "Converza provides AI agents (currently Milo for marketing, Sleyz for sales, and Vea for video) that generate content, draft replies, and produce video assets on your behalf, based on the business information you provide.",
        ],
      },
      {
        title: "Human Approval",
        content: [
          "All content, replies, and assets generated by Converza's agents are staged for your review before anything is sent to a customer, published externally, or otherwise acted upon. You are responsible for reviewing and approving outputs before they go external. Converza is not responsible for content you chose to approve.",
        ],
      },
      {
        title: "Your Account",
        content: [
          "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately of any unauthorized use.",
        ],
      },
      {
        title: "Payment",
        content: [
          "Paid plans are billed according to the plan you select at signup. During pilot arrangements, invoicing may be handled manually. Fees are non-refundable except as required by law or as otherwise agreed in writing.",
        ],
      },
      {
        title: "Your Content and Generated Content",
        content: [
          "You retain ownership of the business information and materials you provide to Converza. Subject to your payment obligations, you own the content, replies, and video assets generated for your business through the Service.",
        ],
      },
      {
        title: "Acceptable Use",
        content: [
          "You agree not to use the Service to generate content that is illegal, fraudulent, deceptive, or that violates the rights of others. You are responsible for ensuring your use of the Service complies with applicable law, including advertising and consumer protection rules in the markets you operate in.",
        ],
      },
      {
        title: "No Guaranteed Results",
        content: [
          "Converza generates content and recommendations using AI models, which may occasionally produce errors or imperfect output. We do not guarantee specific business results, revenue, or performance outcomes from using the Service. This is why every output passes through your review before anything goes external.",
        ],
      },
      {
        title: "Limitation of Liability",
        content: [
          "To the maximum extent permitted by law, Converza is not liable for indirect, incidental, or consequential damages arising from your use of the Service. Our total liability for any claim is limited to the amount you paid us in the preceding three months.",
        ],
      },
      {
        title: "Termination",
        content: [
          "You may cancel your account at any time. We may suspend or terminate accounts that violate these Terms.",
        ],
      },
      {
        title: "Changes to These Terms",
        content: [
          "We may update these Terms from time to time. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.",
        ],
      },
      {
        title: "Governing Law",
        content: [
          "These Terms are governed by the laws of the Republic of Uzbekistan, without regard to conflict of law principles. Confirm jurisdiction once formal entity registration is complete.",
        ],
      },
      {
        title: "Contact",
        content: [
          "Questions about these Terms can be directed to the contact details on our Contact page.",
        ],
        links: [{ label: "Open Contact page", href: "/contact" }],
      },
    ],
  },
  legal: {
    eyebrow: "Company",
    title: "Legal",
    sections: [
      {
        title: "Company Information",
        content: [
          "Converza",
          "Legal entity name and registration number - to be added once formal business registration is complete.",
          "1st passage Ubay, Arifov Street 30, Tashkent, Uzbekistan",
        ],
      },
      {
        title: "Copyright",
        content: [
          "All content, design, and software on this platform, excluding content generated for individual customer accounts, is the property of Converza. Unauthorized reproduction or distribution is prohibited.",
        ],
      },
      {
        title: "Governing Law and Disputes",
        content: [
          "These terms and all legal notices on this site are governed by the laws of the Republic of Uzbekistan. Any disputes arising from use of the Service will be resolved through the courts of Uzbekistan, unless otherwise required by applicable law.",
        ],
      },
      {
        title: "Severability",
        content: [
          "If any provision of our Terms of Service or Privacy Policy is found unenforceable, the remaining provisions continue in full effect.",
        ],
      },
      {
        title: "Related Documents",
        content: ["See our Privacy Policy and Terms of Service for full details on data handling and service terms."],
        links: [
          { label: "Privacy Policy", href: "/privacy" },
          { label: "Terms of Service", href: "/terms" },
        ],
      },
    ],
  },
  contact: {
    eyebrow: "Support",
    title: "Contact",
    introduction: "Reach the Converza team directly using the details below.",
    sections: [
      {
        title: "Phone",
        content: ["+998 77 177 78 10"],
        links: [{ label: "+998 77 177 78 10", href: "tel:+998771777810" }],
      },
      {
        title: "Address",
        content: ["1st passage Ubay, Arifov Street 30", "Tashkent, Uzbekistan"],
      },
      {
        title: "Telegram",
        content: ["@converza_ai"],
        links: [{ label: "@converza_ai", href: "https://t.me/converza_ai" }],
      },
    ],
    closing: "For account or billing questions, reach out via phone or Telegram above.",
  },
  socials: {
    eyebrow: "Follow",
    title: "Socials",
    introduction: "Follow Converza for product updates, launch notes, and practical field reports.",
    sections: [
      {
        title: "Telegram",
        content: ["@converza_ai"],
        links: [{ label: "@converza_ai", href: "https://t.me/converza_ai" }],
      },
      {
        title: "Instagram",
        content: ["converza.ai"],
        links: [{ label: "converza.ai", href: "https://instagram.com/converza.ai" }],
      },
      {
        title: "X",
        content: ["@getconverza"],
        links: [{ label: "@getconverza", href: "https://x.com/getconverza" }],
      },
    ],
  },
};

const footerRoutes: Record<string, string> = {
  "Privacy Policy": "/privacy",
  "Terms of Service": "/terms",
  Legal: "/legal",
  Contact: "/contact",
  Socials: "/socials",
};

export function getFooterLinkHref(label: string) {
  return footerRoutes[label] ?? "#";
}
